"""Qualitative structure tests for step computeCompleteness.

Generated by explorations/generateStepTests.py, which introspects the step's declared output
data files. Every assertion below is derived from the data, not from a reading of the code.
"""

import json
import os

import subprocess

import numpy as np
import pandas as pd
import pytest

S_STEP_DIR = os.path.dirname(os.path.abspath(__file__))
S_REPO_ROOT = os.path.dirname(S_STEP_DIR)
with open(os.path.join(S_STEP_DIR, "testStandards.json")) as _oFile:
    DICT_STANDARDS = json.load(_oFile)
LIST_FILES = sorted(DICT_STANDARDS["dictFiles"].keys())


def fsResolve(sRelPath):
    """Absolute path to a declared output file, resolved from the step directory."""
    return os.path.normpath(os.path.join(S_STEP_DIR, sRelPath))


@pytest.mark.parametrize("sRelPath", LIST_FILES)
def test_recorded_structure_is_present(sRelPath):
    """The columns, JSON keys or array names that downstream steps bind to still exist."""
    dictStd = DICT_STANDARDS["dictFiles"][sRelPath]
    sPath = fsResolve(sRelPath)
    if dictStd["sKind"] == "csv":
        saActual = set(pd.read_csv(sPath, nrows=1).columns)
        saMissing = set(dictStd["saColumns"]) - saActual
        assert not saMissing, f"{sRelPath} lost columns: {sorted(saMissing)}"
    elif dictStd["sKind"] == "npz":
        saActual = set(np.load(sPath, allow_pickle=True).files)
        saMissing = set(dictStd["saArrays"]) - saActual
        assert not saMissing, f"{sRelPath} lost arrays: {sorted(saMissing)}"
    else:
        with open(sPath) as oFile:
            saActual = set(json.load(oFile).keys())
        saMissing = set(dictStd["saTopLevelKeys"]) - saActual
        assert not saMissing, f"{sRelPath} lost top-level keys: {sorted(saMissing)}"


@pytest.mark.parametrize("sRelPath", LIST_FILES)
def test_recorded_numeric_json_paths_are_present(sRelPath):
    """Nested JSON paths that carry the step's results are still reachable."""
    dictStd = DICT_STANDARDS["dictFiles"][sRelPath]
    if dictStd["sKind"] != "json":
        pytest.skip("not a JSON output")
    with open(fsResolve(sRelPath)) as oFile:
        dictData = json.load(oFile)
    for sPathKey in dictStd["dictNumbers"]:
        oNode = dictData
        for sPart in sPathKey.split("."):
            assert isinstance(oNode, dict) and sPart in oNode, sPathKey
            oNode = oNode[sPart]
