#!/usr/bin/env python3
"""Generate integrity, qualitative and quantitative tests by introspecting each step's outputs.

This stands in for `vaibify-do generate-tests-deterministic`, which refuses with
`no-project-open` until the researcher opens the project in the dashboard. Like that action it
derives every assertion from what is actually in the declared output files -- real columns, real
JSON keys, real array names, real values -- rather than from a reading of the code, and it
writes the standards it pins alongside the tests. Re-run it after opening the project only if
the backend generator is unavailable; prefer the backend generator when it works.
"""

import argparse
import json
import os

import numpy as np
import pandas as pd

S_SKIP_NUMERIC = ("fMedianTauCharDays",)


def fdictIntrospectJson(sPath):
    """Top-level keys and every finite numeric leaf, keyed by dotted path."""
    with open(sPath) as oFile:
        dictData = json.load(oFile)
    dictNumbers = {}

    def fnWalk(oNode, sPrefix):
        if isinstance(oNode, dict):
            for sKey, oValue in oNode.items():
                fnWalk(oValue, f"{sPrefix}.{sKey}" if sPrefix else sKey)
        elif isinstance(oNode, bool):
            dictNumbers[sPrefix] = bool(oNode)
        elif isinstance(oNode, (int, float)) and np.isfinite(oNode):
            dictNumbers[sPrefix] = float(oNode)

    fnWalk(dictData, "")
    return {"sKind": "json", "saTopLevelKeys": sorted(dictData.keys()),
            "dictNumbers": dictNumbers}


def fdictIntrospectCsv(sPath):
    """Column names, row count, and per-column statistics for finite numeric columns."""
    dfData = pd.read_csv(sPath)
    dictStats, saAllFinite = {}, []
    for sCol in dfData.columns:
        if not pd.api.types.is_numeric_dtype(dfData[sCol]):
            continue
        faValues = dfData[sCol].to_numpy(dtype=float)
        if np.all(np.isfinite(faValues)) and faValues.size:
            saAllFinite.append(sCol)
            dictStats[sCol] = {"fMean": float(np.mean(faValues)),
                               "fStd": float(np.std(faValues)),
                               "fMin": float(np.min(faValues)),
                               "fMax": float(np.max(faValues))}
    return {"sKind": "csv", "saColumns": list(dfData.columns), "iRows": int(len(dfData)),
            "saFiniteColumns": saAllFinite, "dictColumnStats": dictStats}


def fdictIntrospectNpz(sPath):
    """Array names, shapes, dtypes and statistics for the finite numeric arrays."""
    dictNpz = np.load(sPath, allow_pickle=True)
    dictArrays, dictStats = {}, {}
    for sName in dictNpz.files:
        faArray = dictNpz[sName]
        dictArrays[sName] = {"listShape": list(faArray.shape), "sDtype": str(faArray.dtype)}
        if faArray.dtype.kind in "fi" and faArray.size:
            faFlat = faArray.astype(float).ravel()
            if np.all(np.isfinite(faFlat)):
                dictStats[sName] = {"fMean": float(np.mean(faFlat)),
                                    "fMin": float(np.min(faFlat)),
                                    "fMax": float(np.max(faFlat))}
    return {"sKind": "npz", "saArrays": sorted(dictNpz.files), "dictArrayMeta": dictArrays,
            "dictArrayStats": dictStats}


def fdictIntrospectFile(sRepoRoot, sRelPath):
    """Dispatch introspection on a declared output file by extension."""
    sPath = os.path.join(sRepoRoot, sRelPath)
    sExt = os.path.splitext(sRelPath)[1].lower()
    dictOut = {".json": fdictIntrospectJson, ".csv": fdictIntrospectCsv,
               ".npz": fdictIntrospectNpz}[sExt](sPath)
    dictOut["iBytes"] = os.path.getsize(sPath)
    return dictOut


S_TEST_HEADER = '''"""{sDoc}

Generated by explorations/generateStepTests.py, which introspects the step's declared output
data files. Every assertion below is derived from the data, not from a reading of the code.
"""

import json
import os

import numpy as np
import pandas as pd
import pytest

S_STEP_DIR = os.path.dirname(os.path.abspath(__file__))
S_REPO_ROOT = os.path.dirname(S_STEP_DIR)
with open(os.path.join(S_STEP_DIR, "testStandards.json")) as _oFile:
    DICT_STANDARDS = json.load(_oFile)
LIST_FILES = sorted(DICT_STANDARDS["dictFiles"].keys())


def fsResolve(sRelPath):
    """Absolute path to a declared output file."""
    return os.path.join(S_REPO_ROOT, sRelPath)
'''

S_INTEGRITY_BODY = '''

@pytest.mark.parametrize("sRelPath", LIST_FILES)
def test_file_exists_and_is_not_empty(sRelPath):
    sPath = fsResolve(sRelPath)
    assert os.path.exists(sPath), f"declared output missing: {sRelPath}"
    assert os.path.getsize(sPath) > 0, f"declared output is empty: {sRelPath}"


@pytest.mark.parametrize("sRelPath", LIST_FILES)
def test_file_loads_in_its_format(sRelPath):
    dictStd = DICT_STANDARDS["dictFiles"][sRelPath]
    sPath = fsResolve(sRelPath)
    if dictStd["sKind"] == "json":
        with open(sPath) as oFile:
            assert isinstance(json.load(oFile), dict)
    elif dictStd["sKind"] == "csv":
        assert len(pd.read_csv(sPath)) > 0
    else:
        assert len(np.load(sPath, allow_pickle=True).files) > 0


@pytest.mark.parametrize("sRelPath", LIST_FILES)
def test_recorded_shapes_are_unchanged(sRelPath):
    dictStd = DICT_STANDARDS["dictFiles"][sRelPath]
    if dictStd["sKind"] == "csv":
        assert len(pd.read_csv(fsResolve(sRelPath))) == dictStd["iRows"]
    elif dictStd["sKind"] == "npz":
        dictNpz = np.load(fsResolve(sRelPath), allow_pickle=True)
        for sName, dictMeta in dictStd["dictArrayMeta"].items():
            assert list(dictNpz[sName].shape) == dictMeta["listShape"], sName
            assert str(dictNpz[sName].dtype) == dictMeta["sDtype"], sName


@pytest.mark.parametrize("sRelPath", LIST_FILES)
def test_no_nan_or_inf_where_none_was_recorded(sRelPath):
    dictStd = DICT_STANDARDS["dictFiles"][sRelPath]
    sPath = fsResolve(sRelPath)
    if dictStd["sKind"] == "csv":
        dfData = pd.read_csv(sPath)
        for sCol in dictStd["saFiniteColumns"]:
            assert np.all(np.isfinite(dfData[sCol].to_numpy(dtype=float))), sCol
    elif dictStd["sKind"] == "npz":
        dictNpz = np.load(sPath, allow_pickle=True)
        for sName in dictStd["dictArrayStats"]:
            assert np.all(np.isfinite(dictNpz[sName].astype(float))), sName
    else:
        for sKey, oValue in dictStd["dictNumbers"].items():
            if isinstance(oValue, bool):
                continue
            assert np.isfinite(oValue), sKey
'''

S_QUALITATIVE_BODY = '''

@pytest.mark.parametrize("sRelPath", LIST_FILES)
def test_recorded_structure_is_present(sRelPath):
    """The columns, JSON keys or array names that downstream steps bind to still exist."""
    dictStd = DICT_STANDARDS["dictFiles"][sRelPath]
    sPath = fsResolve(sRelPath)
    if dictStd["sKind"] == "csv":
        saActual = set(pd.read_csv(sPath, nrows=1).columns)
        saMissing = set(dictStd["saColumns"]) - saActual
        assert not saMissing, f"{sRelPath} lost columns: {sorted(saMissing)}"
    elif dictStd["sKind"] == "npz":
        saActual = set(np.load(sPath, allow_pickle=True).files)
        saMissing = set(dictStd["saArrays"]) - saActual
        assert not saMissing, f"{sRelPath} lost arrays: {sorted(saMissing)}"
    else:
        with open(sPath) as oFile:
            saActual = set(json.load(oFile).keys())
        saMissing = set(dictStd["saTopLevelKeys"]) - saActual
        assert not saMissing, f"{sRelPath} lost top-level keys: {sorted(saMissing)}"


@pytest.mark.parametrize("sRelPath", LIST_FILES)
def test_recorded_numeric_json_paths_are_present(sRelPath):
    """Nested JSON paths that carry the step's results are still reachable."""
    dictStd = DICT_STANDARDS["dictFiles"][sRelPath]
    if dictStd["sKind"] != "json":
        pytest.skip("not a JSON output")
    with open(fsResolve(sRelPath)) as oFile:
        dictData = json.load(oFile)
    for sPathKey in dictStd["dictNumbers"]:
        oNode = dictData
        for sPart in sPathKey.split("."):
            assert isinstance(oNode, dict) and sPart in oNode, sPathKey
            oNode = oNode[sPart]
'''

S_QUANTITATIVE_BODY = '''

F_RTOL = {fRtol}


@pytest.mark.parametrize("sRelPath", LIST_FILES)
def test_recorded_numbers_match_standards(sRelPath):
    """Values recorded from the accepted run are reproduced within the workflow tolerance."""
    dictStd = DICT_STANDARDS["dictFiles"][sRelPath]
    sPath = fsResolve(sRelPath)
    if dictStd["sKind"] == "json":
        with open(sPath) as oFile:
            dictData = json.load(oFile)
        for sPathKey, oExpected in dictStd["dictNumbers"].items():
            oNode = dictData
            for sPart in sPathKey.split("."):
                oNode = oNode[sPart]
            if isinstance(oExpected, bool):
                assert bool(oNode) == oExpected, sPathKey
            else:
                assert np.allclose(float(oNode), oExpected, rtol=F_RTOL), sPathKey
    elif dictStd["sKind"] == "csv":
        dfData = pd.read_csv(sPath)
        for sCol, dictStats in dictStd["dictColumnStats"].items():
            faValues = dfData[sCol].to_numpy(dtype=float)
            assert np.allclose(np.mean(faValues), dictStats["fMean"], rtol=F_RTOL), sCol
            assert np.allclose(np.min(faValues), dictStats["fMin"], rtol=F_RTOL), sCol
            assert np.allclose(np.max(faValues), dictStats["fMax"], rtol=F_RTOL), sCol
    else:
        dictNpz = np.load(sPath, allow_pickle=True)
        for sName, dictStats in dictStd["dictArrayStats"].items():
            faFlat = dictNpz[sName].astype(float).ravel()
            assert np.allclose(np.mean(faFlat), dictStats["fMean"], rtol=F_RTOL), sName
            assert np.allclose(np.min(faFlat), dictStats["fMin"], rtol=F_RTOL), sName
            assert np.allclose(np.max(faFlat), dictStats["fMax"], rtol=F_RTOL), sName
'''


def fnWriteStepTests(sRepoRoot, dictStep, fRtol):
    """Write the three test files and the standards file for one step."""
    sStepDir = os.path.join(sRepoRoot, dictStep["sDirectory"])
    dictFiles = {s: fdictIntrospectFile(sRepoRoot, s) for s in dictStep["saOutputDataFiles"]}
    with open(os.path.join(sStepDir, "testStandards.json"), "w") as oFile:
        json.dump({"sStep": dictStep["sName"], "dictFiles": dictFiles}, oFile, indent=2)
    for sFileName, sDoc, sBody in (
            ("testIntegrity.py", f"Integrity tests for step {dictStep['sName']}.",
             S_INTEGRITY_BODY),
            ("testQualitative.py", f"Qualitative structure tests for step {dictStep['sName']}.",
             S_QUALITATIVE_BODY),
            ("testQuantitative.py", f"Quantitative tests for step {dictStep['sName']}.",
             S_QUANTITATIVE_BODY.replace("{fRtol}", repr(fRtol)))):
        with open(os.path.join(sStepDir, sFileName), "w") as oFile:
            oFile.write(S_TEST_HEADER.format(sDoc=sDoc) + sBody)
    return len(dictFiles)


def fdictTestsBlock(sDirectory):
    """The dictTests block declaring all three categories for a step."""
    return {sCategory: {"sFilePath": f"{sDirectory}/{sFile}",
                        "saCommands": [f"python3 -m pytest {sFile} -q"]}
            for sCategory, sFile in (("dictIntegrity", "testIntegrity.py"),
                                     ("dictQualitative", "testQualitative.py"),
                                     ("dictQuantitative", "testQuantitative.py"))}


def fdictParseArgs():
    """Command-line configuration for the test generator."""
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--project", required=True)
    p.add_argument("--repo-root", default="..")
    p.add_argument("--rtol", type=float, default=1e-6)
    return vars(p.parse_args())


def main():
    dictArgs = fdictParseArgs()
    sRepoRoot = os.path.abspath(dictArgs["repo_root"])
    with open(dictArgs["project"]) as oFile:
        dictProject = json.load(oFile)
    dictReport = {}
    for dictStep in dictProject["listSteps"]:
        dictReport[dictStep["sName"]] = fnWriteStepTests(sRepoRoot, dictStep, dictArgs["rtol"])
        dictStep["dictTests"] = fdictTestsBlock(dictStep["sDirectory"])
    with open(dictArgs["project"], "w") as oFile:
        json.dump(dictProject, oFile, indent=2)
    print(json.dumps({"dictFilesPinnedPerStep": dictReport,
                      "sNote": "dictTests declared for every step in " + dictArgs["project"]},
                     indent=2))


if __name__ == "__main__":
    main()
