"""Quantitative tests for step verifyAgainstPublished.

Generated by explorations/generateStepTests.py, which introspects the step's declared output
data files. Every assertion below is derived from the data, not from a reading of the code.
"""

import json
import os

import subprocess

import numpy as np
import pandas as pd
import pytest

S_STEP_DIR = os.path.dirname(os.path.abspath(__file__))
S_REPO_ROOT = os.path.dirname(S_STEP_DIR)
with open(os.path.join(S_STEP_DIR, "testStandards.json")) as _oFile:
    DICT_STANDARDS = json.load(_oFile)
LIST_FILES = sorted(DICT_STANDARDS["dictFiles"].keys())


def fsResolve(sRelPath):
    """Absolute path to a declared output file, resolved from the step directory."""
    return os.path.normpath(os.path.join(S_STEP_DIR, sRelPath))


F_RTOL = 1e-06


@pytest.mark.parametrize("sRelPath", LIST_FILES)
def test_recorded_numbers_match_standards(sRelPath):
    """Values recorded from the accepted run are reproduced within the workflow tolerance."""
    dictStd = DICT_STANDARDS["dictFiles"][sRelPath]
    sPath = fsResolve(sRelPath)
    if dictStd["sKind"] == "json":
        with open(sPath) as oFile:
            dictData = json.load(oFile)
        for sPathKey, oExpected in dictStd["dictNumbers"].items():
            oNode = dictData
            for sPart in sPathKey.split("."):
                oNode = oNode[sPart]
            if isinstance(oExpected, bool):
                assert bool(oNode) == oExpected, sPathKey
            else:
                assert np.allclose(float(oNode), oExpected, rtol=F_RTOL), sPathKey
    elif dictStd["sKind"] == "csv":
        dfData = pd.read_csv(sPath)
        for sCol, dictStats in dictStd["dictColumnStats"].items():
            faValues = dfData[sCol].to_numpy(dtype=float)
            assert np.allclose(np.mean(faValues), dictStats["fMean"], rtol=F_RTOL), sCol
            assert np.allclose(np.min(faValues), dictStats["fMin"], rtol=F_RTOL), sCol
            assert np.allclose(np.max(faValues), dictStats["fMax"], rtol=F_RTOL), sCol
    else:
        dictNpz = np.load(sPath, allow_pickle=True)
        for sName, dictStats in dictStd["dictArrayStats"].items():
            faFlat = dictNpz[sName].astype(float).ravel()
            assert np.allclose(np.mean(faFlat), dictStats["fMean"], rtol=F_RTOL), sName
            assert np.allclose(np.min(faFlat), dictStats["fMin"], rtol=F_RTOL), sName
            assert np.allclose(np.max(faFlat), dictStats["fMax"], rtol=F_RTOL), sName
