"""Integrity tests for step sampleOccurrencePosterior.

Generated by explorations/generateStepTests.py, which introspects the step's declared output
data files. Every assertion below is derived from the data, not from a reading of the code.
"""

import json
import os

import subprocess

import numpy as np
import pandas as pd
import pytest

S_STEP_DIR = os.path.dirname(os.path.abspath(__file__))
S_REPO_ROOT = os.path.dirname(S_STEP_DIR)
with open(os.path.join(S_STEP_DIR, "testStandards.json")) as _oFile:
    DICT_STANDARDS = json.load(_oFile)
LIST_FILES = sorted(DICT_STANDARDS["dictFiles"].keys())


def fsResolve(sRelPath):
    """Absolute path to a declared output file, resolved from the step directory."""
    return os.path.normpath(os.path.join(S_STEP_DIR, sRelPath))


@pytest.mark.parametrize("sRelPath", LIST_FILES)
def test_file_exists_and_is_not_empty(sRelPath):
    sPath = fsResolve(sRelPath)
    assert os.path.exists(sPath), f"declared output missing: {sRelPath}"
    assert os.path.getsize(sPath) > 0, f"declared output is empty: {sRelPath}"


@pytest.mark.parametrize("sRelPath", LIST_FILES)
def test_file_loads_in_its_format(sRelPath):
    dictStd = DICT_STANDARDS["dictFiles"][sRelPath]
    sPath = fsResolve(sRelPath)
    if dictStd["sKind"] == "json":
        with open(sPath) as oFile:
            assert isinstance(json.load(oFile), dict)
    elif dictStd["sKind"] == "csv":
        assert len(pd.read_csv(sPath)) > 0
    else:
        assert len(np.load(sPath, allow_pickle=True).files) > 0


@pytest.mark.parametrize("sRelPath", LIST_FILES)
def test_recorded_shapes_are_unchanged(sRelPath):
    dictStd = DICT_STANDARDS["dictFiles"][sRelPath]
    if dictStd["sKind"] == "csv":
        assert len(pd.read_csv(fsResolve(sRelPath))) == dictStd["iRows"]
    elif dictStd["sKind"] == "npz":
        dictNpz = np.load(fsResolve(sRelPath), allow_pickle=True)
        for sName, dictMeta in dictStd["dictArrayMeta"].items():
            assert list(dictNpz[sName].shape) == dictMeta["listShape"], sName
            assert str(dictNpz[sName].dtype) == dictMeta["sDtype"], sName


@pytest.mark.parametrize("sRelPath", LIST_FILES)
def test_no_nan_or_inf_where_none_was_recorded(sRelPath):
    dictStd = DICT_STANDARDS["dictFiles"][sRelPath]
    sPath = fsResolve(sRelPath)
    if dictStd["sKind"] == "csv":
        dfData = pd.read_csv(sPath)
        for sCol in dictStd["saFiniteColumns"]:
            assert np.all(np.isfinite(dfData[sCol].to_numpy(dtype=float))), sCol
    elif dictStd["sKind"] == "npz":
        dictNpz = np.load(sPath, allow_pickle=True)
        for sName in dictStd["dictArrayStats"]:
            assert np.all(np.isfinite(dictNpz[sName].astype(float))), sName
    else:
        for sKey, oValue in dictStd["dictNumbers"].items():
            if isinstance(oValue, bool):
                continue
            assert np.isfinite(oValue), sKey
